export const LOADING = {
	START_LOADING: 'START_LOADING',
	STOP_LOADING: 'STOP_LOADING'
};

export const POKEMON = {
	ADD: 'ADD_POKEMON',
	CLEAR: 'CLEAR_POKEMON',
	INCREMENT_OFFSET: 'INCREMENT_OFFSET'
}